// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0HICXr_ZNr9aLAJfGabwX80qfQ8Xtzk',
    appId: '1:626087765038:web:8cf5a9147195ca53382bbf',
    messagingSenderId: '626087765038',
    projectId: 'eatmeh-a70a6',
    authDomain: 'eatmeh-a70a6.firebaseapp.com',
    databaseURL: 'https://eatmeh-a70a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eatmeh-a70a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCgDzGijPTI_TeX_EN_J18Fnw2aQULb3c',
    appId: '1:626087765038:android:59a2dc3124de8133382bbf',
    messagingSenderId: '626087765038',
    projectId: 'eatmeh-a70a6',
    databaseURL: 'https://eatmeh-a70a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eatmeh-a70a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2qplIsDmbIh_OlZQ0KwRq3bAl0yU0qQw',
    appId: '1:626087765038:ios:39a2d35675dff25c382bbf',
    messagingSenderId: '626087765038',
    projectId: 'eatmeh-a70a6',
    databaseURL: 'https://eatmeh-a70a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eatmeh-a70a6.firebasestorage.app',
    iosBundleId: 'com.example.eatmehv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2qplIsDmbIh_OlZQ0KwRq3bAl0yU0qQw',
    appId: '1:626087765038:ios:39a2d35675dff25c382bbf',
    messagingSenderId: '626087765038',
    projectId: 'eatmeh-a70a6',
    databaseURL: 'https://eatmeh-a70a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eatmeh-a70a6.firebasestorage.app',
    iosBundleId: 'com.example.eatmehv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo0HICXr_ZNr9aLAJfGabwX80qfQ8Xtzk',
    appId: '1:626087765038:web:d501d2ad353e3908382bbf',
    messagingSenderId: '626087765038',
    projectId: 'eatmeh-a70a6',
    authDomain: 'eatmeh-a70a6.firebaseapp.com',
    databaseURL: 'https://eatmeh-a70a6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eatmeh-a70a6.firebasestorage.app',
  );
}
